config/routes.rb
Rails.application.routes.draw do
  get 'reservations/create'

  devise_for :owners
  get 'welcome/index'

  devise_for :customers
  resources :categories,only: [:index, :show]

  authenticated :customer do
    root 'places#index', as: 'authenticated_root_customer'
  end

  authenticated :owner do
    root 'places#index', as: 'authenticated_root_owner'
  end

  root 'welcome#index'

  resources :places do
    resources :comments, only: [:create, :destroy]
    resources :reservations, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  def places
    Place.where(category_id: id)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :place
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reservations
  has_many :comments
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :places
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/place.rb
class Place < ApplicationRecord
 has_many :comments
 belongs_to :owner
 has_many :reservations
  def category
    Category.find(category_id)
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :place
  belongs_to :customer

  validates :date, presence: true
  validates :number_of_people, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_customer!


  def create
    @place = Place.find(params[:place_id])
    @comment = @place.comments.new(comment_params)
    @comment.customer = current_customer
    @comment.place_id = @place.id

    if @comment.save
      CommentMailer.new_comment(@place).deliver_now
      redirect_to place_path(@place)
    else
      render 'new'
    end
  end

  def destroy
    @place = Place.find(params[:place_id])
    @comment =  Comment.find(params[:id])
    @comment.destroy
    redirect_to @place
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_owner!, except: [:index,:show]
  before_action :find_place, only: [:show, :edit, :update, :destroy]
  before_action :authorize_owner!, only: [:edit, :update, :destroy]

  def index
    @places = Place.all
  end

  def new
    @place = Place.new
    load_categories
  end

  def create
    @place = current_owner.places.build(places_params)

    if @place.save
      flash[:success]="Successfully created!"
      redirect_to @place
    else
      load_categories
      render 'new'
    end
  end

  def show
    @place= Place.find(params[:id])
  end

  def edit
    load_categories
  end

  def update
    if @place.update(places_params)
      redirect_to @place
    else
      load_categories
      render 'edit'
    end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to root_path
  end

  private
  # giriş yapanın edit yetkisi olup olmadığını kontrol eder.
  def authorize_owner!
    redirect_to root_path, notice: "Not Authorized" unless @place.owner_id == current_owner.id
  end

  def find_place
    @place = Place.find(params[:id])
  end

  def places_params
    params.require(:place).permit(:name,:address,:astablished_at, :phone_number, :contact_mail, :city, :description, :category_id)
  end

  def load_categories
    @categories = Category.all.collect { |c| [c.title, c.id]}
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def create
    @place = Place.find(params[:place_id])
    @reservation = @place.reservations.new(reservation_params)
    @reservation.customer = current_customer

    if @reservation.save
      redirect_to @place
    else
      redirect_to @place, notice: " Not Valid!"
    end
  end

  def destroy
    @place = Place.find(params[:place_id])
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to @place
  end

  private

  def reservation_params
    params.require(:reservation).permit(:date, :number_of_people)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/index.html.erb
<h1>Listing Categories</h1>
<% @categories.each do |category|%>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%=link_to category.title, category_path(category) %></h3>
      </div>
    </div>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.title%></h1>
<p><%= @category.description %></p>
<p><%= @category.color%></p>

<p><b>Listing Ideas From <%= @category.title%></b></p>

<% @category.places.each do |place| %>
    <p><%=link_to place.name, place_path(place) %></p>
<% end %>

<%= link_to "Back", categories_path %>

app/views/comments/_form.html.erb
<%= form_for [@place, @place.comments.build] do |f| %>

    <%= f.text_area :body, placeholder:'comment' %><br>
    <%= f.button :submit %>
<% end %>

app/views/layouts/_flash.html.erb
<% if !flash.empty? %>
    <div id="flash">
      <% flash.keys.each do |k| %>
          <div class="alert alert-warning" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            <%= flash[k] %>
          </div>
      <% end %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlaceBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          <img alt="PlaceBoard" src="...">
        </a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Places", places_path%> <span class="sr-only">(current)</span></li>
          <li><%= link_to "Categories", categories_path%></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_owner.present? %>
            <li><a href="#">Welcome <%= current_owner.email%></a></li>
            <li><%= link_to "New Place", new_place_path%></li>
            <li><%= link_to "Log Out", destroy_owner_session_path, method: :delete%></li>
          <% elsif current_customer.present? %>
              <li><a href="#">Welcome <%= current_customer.email%></a></li>
              <li><%= link_to "Log Out", destroy_customer_session_path, method: :delete%></li>
          <% else %>
            <li><%= link_to "Register Owner", new_owner_registration_path%></li>
            <li><%= link_to "Register Customer", new_customer_registration_path%></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
  <nav class="content">
    <%= render 'layouts/flash' %>
    <%= yield %>
  </nav>
  </body>
</html>

app/views/places/_form.html.erb
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<%= form_for @place do |f| %>
    Name:
    <%= f.text_field :name, placeholder:'name' %><br>
    Address:
    <%= f.text_field :address, placeholder:'address' %><br>
    City:
    <%= f.text_field :city, placeholder:'city' %><br>
    Description:
    <%= f.text_field :description, placeholder:'description' %><br>
    Category:
    <%= f.select :category_id, @categories%><br><br>
    <%= f.button :submit %>
<% end %>

app/views/places/edit.html.erb
<h1>Edit <%= @place.name %></h1>
<% if @place.errors.any? %>
    <h1><%=@place.errors.full_messages.join(", ") %></h1>
<%end%>

<form action="<%= place_path @place %>" method="post">
  <input type="hidden" name="_method" value="put">

  <%= render 'form' %>
</form>

app/views/places/index.html.erb
<div id="categories" class="nav-content">
  <% @places.each do |place| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><a href="/places/<%= place.id %>"><%= place.name %></a></h3>
        </div>
        <div class="panel-body">
          <%= place.description %>
        </div>
      </div>
  <% end %>
</div>

app/views/places/new.html.erb
<h1>Create new Place</h1>
<% if @place.errors.any? %>
    <h1><%=@place.errors.full_messages.join(", ") %></h1>

<%end%>
<form action="<%= places_path %>" method="post">

  <%= render 'form' %>
</form>

app/views/places/show.html.erb
<h4>Display Place</h4>

<b>Id: </b><%= @place.id %><br />
<b>Name: </b><%= @place.name %><br />
<b>Description: </b><%= @place.description %><br />
<b>Category: </b><%= @place.category.title %><br />
<br/><br/>

<% if current_customer.present? %>
    <button type="button" data-toggle="modal" data-target="#myModal">
      New Reservation
    </button>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Rezervation</h4>
          </div>
          <div class="modal-body">
            <%= render 'reservations/form' %>
          </div>
        </div>
      </div>
    </div>
    <% if current_owner == @place.owner %>

    <% end %>
<% end %>
<a href="/places">Back to place list</a>
<% if current_owner.present? %>
  <% if current_owner.id == @place.owner_id %>
    <a href="<%= edit_place_path(@place) %>">Edit</a>
    <%=link_to "Delete", place_path(@place), method: :delete, data: {confirm:  "Are you sure?"} %>
  <% end %>
<% end %>
  <% @place.reservations.reject{ |reservation| reservation.id.nil? }.each do |reservation| %>
        <br><br>
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">Your Reservation</h3>
          </div>
          <div class="panel-body">
            <p>Date : <%= reservation.date%></p>
            <p>Number of people : <%= reservation.number_of_people%></p>
            <hr>
            <%= link_to "Delete", place_reservation_path( @place,reservation), method: :delete %>
                </div>
        </div>
      <hr>
  <% end %>

<br><br><br>
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Comments</h2>
  </div>
  <div class="panel-body">
    <% @place.comments.each do |comment| %>
        <p><i><small><%= link_to comment.customer.email,"#" %> says ;</small></i></p>
        <p><%= comment.body%></p>
        <% if current_customer == comment.customer %>
        <small><%= link_to "Delete", place_comment_path(@place, comment) ,method: :delete%></small>
        <% end %>
        <hr>
    <% end %>
    <% if current_customer.present? %>
        <p><i><b>Write a comment:</b></i></p>
        <%= render 'comments/form'%>
    <% end %>
  </div>
</div>

app/views/reservations/_form.html.erb
<%= form_for [@place, @place.reservations.build] do |f| %>
    Date:
    <%= f.datetime_field :date %><br>
    Number Of People:
    <%= f.text_field :number_of_people %><br>
    <%= f.button :submit %>
<% end %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 id="center">Welcome!</h1>
  <p id="center">Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır.</p>
  <p id="center_center"><%= link_to  "Owner Log In", new_owner_session_path, class: 'btn btn-primary btn-lg' %>     ||     <%= link_to  "Customer Log In", new_customer_session_path, class: 'btn btn-primary btn-lg' %></p>
</div>